"""empty message

Revision ID: 3a103f81e97d
Revises: None
Create Date: 2016-05-31 21:56:11.515690

"""

# revision identifiers, used by Alembic.
revision = '3a103f81e97d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journals_costtime', table_name='journals')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_journals_costtime', 'journals', ['costtime'], unique=False)
    ### end Alembic commands ###
