"""empty message

Revision ID: 5a38298967ce
Revises: 3a103f81e97d
Create Date: 2016-06-02 16:54:51.648537

"""

# revision identifiers, used by Alembic.
revision = '5a38298967ce'
down_revision = '3a103f81e97d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_journals_date'), 'journals', ['date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_date'), table_name='journals')
    op.drop_column('journals', 'date')
    ### end Alembic commands ###
